services:
  portfolio-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: durbanod-portfolio
    restart: unless-stopped
    ports:
      - "8383:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio-network:
    driver: bridge
