services:
  angular-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: durbanod-portfolio-ssr
    restart: unless-stopped
    expose:
      - "4000"  
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: durbanod-portfolio-nginx
    restart: unless-stopped
    ports:
      - "8383:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/daniel-urbano-portfolio/browser:/usr/share/nginx/html:ro
    depends_on:
      - angular-ssr
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  portfolio-network:
    driver: bridge
