name: portafolio-deploy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: portafolio
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: angular-migration/package-lock.json
          
      - name: Install dependencies
        run: |
          cd angular-migration
          npm ci
          
      - name: Build Angular app (Production)
        run: |
          cd angular-migration
          npm run build
          echo "✅ Production build completed successfully"
          echo "📦 Build output:"
          ls -la dist/daniel-urbano-portfolio/browser
        env:
          NODE_ENV: production
          
      - name: Prepare deployment files
        run: |
          cd ${{ github.workspace }}
          echo "Current directory contents:"
          ls -la
          echo "Angular build output:"
          ls -la angular-migration/dist/daniel-urbano-portfolio/browser

      - name: Deploy to server
        uses: dannybombastic/ssh-scp-ssh-pipelines@v1.1.5
        with:
            host: ${{ secrets.REMOTE_HOST }}
            port: 8549
            user: ${{ secrets.REMOTE_USER }}
            pass: ${{ secrets.REMOTE_PASS }}
            connect_timeout: 30s
            first_ssh: |
              echo "Cleaning old deployment..."
              rm -rf /home/dannybombastic/durbanod/durbanod/*
              echo "Cleanup completed"
            scp: |
                "angular-migration/dist/daniel-urbano-portfolio/browser/*" => /home/dannybombastic/durbanod/durbanod
            last_ssh: |
                echo "Verifying deployment..."
                ls -la /home/dannybombastic/durbanod/durbanod
                echo "Rebuilding and restarting Docker container..."
                cd /home/dannybombastic/durbanod
                docker compose up -d --build
                echo "Deployment completed successfully!"
                docker compose ps
