name: portafolio-deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: portafolio
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
          
      - name: copy into folder dependencies
        run: |
            echo $PWD
            cd ${{ github.workspace }}
            ls -la

      - name: Publish
        uses: dannybombastic/ssh-scp-ssh-pipelines@v1.1.5
        with:
            host: ${{ secrets.REMOTE_HOST }}
            port: 8549
            user: ${{ secrets.REMOTE_USER }}
            pass: ${{ secrets.REMOTE_PASS }}
            connect_timeout: 30s
            first_ssh: |
              rm -rf /home/dannybombastic/durbanod/durbanod/*
            scp: |
                "./Durbano-portfolio/*" => /home/dannybombastic/durbanod/durbanod
            last_ssh: |
                cd /home/dannybombastic/durbanod
                docker compose up -d --build
