name: portafolio-deploy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: portafolio
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: angular-migration/package-lock.json
          
      - name: Install dependencies
        run: |
          cd angular-migration
          npm install --prefer-offline --no-audit
          
      - name: Build Angular SSR app (Production)
        run: |
          cd angular-migration
          npm run build:ssr
          echo "✅ SSR Production build completed successfully"
          echo "📦 Browser build output:"
          ls -la dist/daniel-urbano-portfolio/browser
          echo "📦 Server build output:"
          ls -la dist/daniel-urbano-portfolio/server
        env:
          NODE_ENV: production
          
      - name: Prepare deployment files
        run: |
          cd angular-migration
          echo "Creating deployment package..."
          echo "Packaging source files for Docker build..."
          tar -czf ../deploy-ssr.tar.gz \
            src/ \
            public/ \
            package*.json \
            angular.json \
            tsconfig*.json \
            Dockerfile \
            docker-compose.yml \
            .dockerignore \
            .eslintrc.json
          cd ..
          echo "✅ Deployment package created"
          ls -lh deploy-ssr.tar.gz

      - name: Deploy SSR to server
        uses: dannybombastic/ssh-scp-ssh-pipelines@v1.1.5
        with:
            host: ${{ secrets.REMOTE_HOST }}
            port: 8549
            user: ${{ secrets.REMOTE_USER }}
            pass: ${{ secrets.REMOTE_PASS }}
            connect_timeout: 30s
            first_ssh: |
              echo "Preparing deployment directory..."
              mkdir -p /home/dannybombastic/durbanod/portfolio-ssr
              cd /home/dannybombastic/durbanod/portfolio-ssr
              echo "Stopping current container..."
              docker compose down 2>/dev/null || true
              echo "Cleaning old files..."
              rm -rf src/ public/ dist/ package*.json angular.json tsconfig*.json Dockerfile docker-compose.yml .dockerignore .eslintrc.json
              echo "✅ Cleanup completed"
            scp: |
                "deploy-ssr.tar.gz" => /home/dannybombastic/durbanod/portfolio-ssr/
            last_ssh: |
                echo "Extracting deployment package..."
                cd /home/dannybombastic/durbanod/portfolio-ssr
                tar -xzf deploy-ssr.tar.gz
                rm deploy-ssr.tar.gz
                echo "✅ Files extracted"
                ls -la
                echo "Building and starting SSR Docker container..."
                docker compose up -d --build
                echo "✅ Deployment completed successfully!"
                docker compose ps
                echo "🔍 Checking SSR server health..."
                sleep 5
                docker compose logs --tail=20
